# Generated by Django 5.0.6 on 2024-06-29 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
        ('musician', '0002_musician_email_musician_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='musician',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='musician.musician'),
        ),
        migrations.AddField(
            model_name='album',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
