# Generated by Django 5.0.6 on 2024-06-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_album_musician_album_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='instrument_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
